server {
    listen 80;

    # Frontend React
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy tới NodeJS API (Tasks)
    location /api-node/ {
        proxy_pass http://node-api:3000/api-node/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy tới Python API (Users + Dashboard)
    location /api-python/ {
        proxy_pass http://python-api:8000/api-python/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
